"""Synthetic ground-truth tests for the Hawkes toolkit.

These tests ARE the deliverable for Phase-3 Task 1: the simulator, the
exponential-kernel MLE, and the model-free count-variance branching
estimator are only trustworthy insofar as they recover known parameters
on data generated by the simulator itself (and, for the trap test, on
data generated by a process that is deliberately NOT Hawkes).
"""
from __future__ import annotations

import numpy as np
import pytest

from microstructure.estimators.hawkes import (
    HawkesFit,
    _nelder_mead,
    branching_count_variance,
    fit_hawkes_exp,
    hawkes_loglik,
    simulate_hawkes_exp,
)

# ---------------------------------------------------------------------------
# Group 0: Nelder-Mead sanity check on a known quadratic (test the optimizer
# itself before trusting it to fit anything statistical).
# ---------------------------------------------------------------------------


def test_nelder_mead_recovers_quadratic_minimum():
    # f(x, y) = (x - 3)^2 + (y + 2)^2 + 7, minimum at (3, -2), f_min = 7.
    def f(p: np.ndarray) -> float:
        return float((p[0] - 3.0) ** 2 + (p[1] + 2.0) ** 2 + 7.0)

    x0 = np.array([0.0, 0.0])
    best_x, best_f, converged = _nelder_mead(f, x0, max_iter=500)
    assert converged
    assert abs(best_x[0] - 3.0) < 1e-3
    assert abs(best_x[1] - (-2.0)) < 1e-3
    assert abs(best_f - 7.0) < 1e-5


def test_nelder_mead_handles_rosenbrock_like_valley():
    # A harder, curved-valley function: minimum at (1, 1), f_min = 0.
    def f(p: np.ndarray) -> float:
        x, y = p
        return float(100.0 * (y - x**2) ** 2 + (1.0 - x) ** 2)

    x0 = np.array([-1.0, 1.5])
    best_x, best_f, _converged = _nelder_mead(f, x0, max_iter=2000)
    assert best_f < 1e-3
    assert abs(best_x[0] - 1.0) < 0.05
    assert abs(best_x[1] - 1.0) < 0.05


# ---------------------------------------------------------------------------
# Group 0b: log-likelihood formula verified against numerical integration
# of the intensity on a tiny hand-checkable case.
# ---------------------------------------------------------------------------


def test_loglik_matches_numerical_intensity_integration():
    """Verify Σ log λ(t_i) − ∫λ(t)dt against brute-force numerical intensity.

    Uses 10 fixed event times (not simulated) so the check is independent
    of the simulator. Integrates λ(t) = mu + Σ alpha*beta*exp(-beta(t-t_i))
    with a fine trapezoid rule over [0, T] and compares to the closed-form
    recursion used in hawkes_loglik.
    """
    times = np.array([1.0, 1.3, 2.1, 2.15, 3.0, 4.4, 4.5, 4.55, 6.0, 8.0])
    t_end = 10.0
    mu, alpha, beta = 0.3, 0.5, 1.5

    ll_closed = hawkes_loglik(times, t_end, mu, alpha, beta)

    # Brute-force: Σ log λ(t_i^-) exactly (no integration needed for the
    # sum term — λ just before each event, using only prior events).
    log_sum = 0.0
    for i, ti in enumerate(times):
        prior = times[:i]
        excitation = np.sum(alpha * beta * np.exp(-beta * (ti - prior))) if i > 0 else 0.0
        log_sum += np.log(mu + excitation)

    # Numerically integrate the compensator ∫_0^T λ(t) dt via fine trapezoid.
    grid = np.linspace(0.0, t_end, 2_000_000)
    excitation_grid = np.zeros_like(grid)
    for ti in times:
        mask = grid > ti
        excitation_grid[mask] += alpha * beta * np.exp(-beta * (grid[mask] - ti))
    lam_grid = mu + excitation_grid
    compensator_numeric = np.trapezoid(lam_grid, grid)

    ll_numeric = log_sum - compensator_numeric

    assert abs(ll_closed - ll_numeric) < 1e-3, (ll_closed, ll_numeric)


# ---------------------------------------------------------------------------
# Group 1: simulate -> fit round trip across 3 seeds.
# ---------------------------------------------------------------------------

TRUE_MU, TRUE_ALPHA, TRUE_BETA = 0.5, 0.4, 2.0
T_END = 200_000.0
FIT_SUBSAMPLE_T = 100_000.0  # per brief: subsample fit tests to first 100k events' worth


def _simulate_and_fit(seed: int) -> tuple[np.ndarray, HawkesFit]:
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    # Subsample to the first FIT_SUBSAMPLE_T seconds of events for MLE speed
    # (full sims are 150-300k events; fitting on ~half keeps the whole
    # suite under the runtime budget while still exercising the estimator
    # at realistic sample size, per the brief's runtime-discipline note).
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    return times, fit


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_mle_recovers_known_parameters(seed):
    _, fit = _simulate_and_fit(seed)
    assert fit.converged
    assert abs(fit.alpha - TRUE_ALPHA) < 0.03, f"seed={seed} alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.05, f"seed={seed} mu={fit.mu}"
    assert abs(fit.beta - TRUE_BETA) / TRUE_BETA < 0.20, f"seed={seed} beta={fit.beta}"


def test_mle_alpha_stable_across_seeds():
    alphas = []
    for seed in (7, 8, 9):
        _, fit = _simulate_and_fit(seed)
        alphas.append(fit.alpha)
    sd = float(np.std(alphas, ddof=1))
    assert sd < 0.02, f"alphas={alphas} sd={sd}"


# ---------------------------------------------------------------------------
# Group 2: count-variance estimator on the same simulations.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_count_variance_recovers_branching_ratio(seed):
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - TRUE_ALPHA) < 0.05, f"seed={seed} n_hat={n_hat}"


def test_count_variance_guards_too_few_windows():
    times = np.array([1.0, 2.0, 3.0])
    with pytest.raises(ValueError):
        branching_count_variance(times, window=1.0, t_end=3.0)


def test_count_variance_guards_zero_variance():
    # Perfectly regular spacing (one event every 1.0s) with window=10.0
    # puts exactly 10 events in every non-overlapping window -> var == 0.
    times = np.arange(0.0, 10_000.0, 1.0)
    with pytest.raises(ValueError):
        branching_count_variance(times, window=10.0, t_end=10_000.0)


# ---------------------------------------------------------------------------
# Group 3: near-critical regime (alpha=0.85) — wider tolerances, documented.
# ---------------------------------------------------------------------------

NEAR_CRITICAL_ALPHA = 0.85


def test_near_critical_mle_recovers_within_widened_tolerance():
    """Near n=1, mu/alpha become weakly identified locally (research/02 §4
    pitfall 5: 'near-unidentifiability at n≈1'); we widen tolerances vs the
    n=0.4 case rather than pretend the estimator is equally sharp everywhere.
    """
    times = simulate_hawkes_exp(TRUE_MU, NEAR_CRITICAL_ALPHA, TRUE_BETA, T_END, seed=11)
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert abs(fit.alpha - NEAR_CRITICAL_ALPHA) < 0.08, f"alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.15, f"mu={fit.mu}"

    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - NEAR_CRITICAL_ALPHA) < 0.12, f"n_hat={n_hat}"


# ---------------------------------------------------------------------------
# Group 4: Poisson refutation test (the Filimonov-Sornette trap).
# ---------------------------------------------------------------------------


def test_poisson_refutation_both_estimators_report_near_zero():
    """A pure Poisson stream (alpha=0) must NOT look self-exciting."""
    rng = np.random.default_rng(21)
    rate = 1.0
    t_end = 200_000.0
    n_expected = int(rate * t_end * 1.05)
    gaps = rng.exponential(1.0 / rate, size=n_expected)
    times = np.cumsum(gaps)
    times = times[times <= t_end]

    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.alpha < 0.05, f"fitted alpha={fit.alpha} on pure Poisson"

    n_hat = branching_count_variance(times, window=500.0, t_end=t_end)
    assert n_hat < 0.05, f"count-variance n_hat={n_hat} on pure Poisson"


def test_regime_switching_poisson_produces_spurious_endogeneity_trap():
    """THE TRAP (Filimonov & Sornette 2015, research/02-hawkes-processes.md,
    'The calibration counterattack' section, §2.4-equivalent discussion):
    n̂ ≈ near-critical can be MANUFACTURED FROM NOTHING. Fitting a Hawkes
    model (or the count-variance estimator) to a regime-switching Poisson
    process — no self-excitation anywhere, only a rate that alternates
    between a low and a high value on a fixed clock — produces a SPURIOUS
    positive branching-ratio estimate, because clustering induced by rate
    non-stationarity is statistically indistinguishable, to both a
    likelihood fit and a count-mean/variance test, from clustering induced
    by genuine self-excitation.

    This is why deseasonalization (fitting or removing a time-varying
    baseline mu(t) BEFORE testing for endogeneity) is not optional: any
    Hawkes/branching-ratio estimate computed on a non-stationary-rate
    series conflates "the rate changes over time" with "events cause more
    events," and the two are observationally similar in aggregate count
    statistics. We assert n_hat > 0.2 here specifically to document that
    the spurious effect is not a rounding error — it is large enough to
    be mistaken for real, moderate endogeneity.
    """
    rng = np.random.default_rng(22)
    low_rate, high_rate = 0.5, 2.0
    regime_len = 5000.0
    t_end = 200_000.0

    times: list[float] = []
    t = 0.0
    regime_start = 0.0
    is_low = True
    while regime_start < t_end:
        rate = low_rate if is_low else high_rate
        regime_end = min(regime_start + regime_len, t_end)
        t = regime_start
        while True:
            t += rng.exponential(1.0 / rate)
            if t >= regime_end:
                break
            times.append(t)
        regime_start = regime_end
        is_low = not is_low

    times_arr = np.asarray(times, dtype=np.float64)

    n_hat = branching_count_variance(times_arr, window=500.0, t_end=t_end)
    assert n_hat > 0.2, (
        f"expected the regime-switching trap to produce spurious n_hat > 0.2, "
        f"got {n_hat}"
    )
